{ userData:
    [ { name: 'George',
        age: 71,
        address: 'Fleet street, 121b',
        willDeliverPizza: true },
      { name: 'Richard',
        age: 81,
        address: 'Bermuda drive, 33',
        willDeliverPizza: false },
      { name: 'Abraham',
        age: 56,
        address: 'Cincinatti Av., 22a',
        willDeliverPizza: true },
      { name: 'Donald',
        age: 71,
        address: undefined,
        willDeliverPizza: 'Unknown' } ],
   highestAge: 81,
   lowestAge: 56 }
