export const person = [{
       id: 1,
       name: "Renata",
       age: 30,
       city: "Berlin",
       country: "Germany",
       email: "renata@gmail.com",
       url: 'http://res.cloudinary.com/dngl5axlu/image/upload/c_scale,h_350/v1529588336/samples/people/kitchen-bar.jpg',
       interests: [ 'yoga', 'food', 'museums', 'drinking', 'sport' ],
       isTraveler: true,

   },
   {
       id: 2,
       name: "Cris",
       age: 35,
       city: "Berlin",
       country: "Germany",
       email: "cris@gmail.com",
       url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529660318/1-10.jpg',
       interests: [ 'yoga', 'food', 'museums','sport', 'books', 'drinking' ],
       isTraveler: true,

   },
   {
       id: 3,
       name: "Rodrigo",
       age: 36,
       city: "Brussels",
       country: "Belgium",
       email: "rodrigo@gmail.com",
       url: 'http://res.cloudinary.com/dngl5axlu/image/upload/c_scale,h_350/v1529588345/samples/people/bicycle.jpg',
       interests: [ 'yoga', 'dancing', 'sport', 'museums', 'food' ],
       isTraveler: true,

   },
   {
     id: 4,
     name: "Ana",
     age: 30,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "ana@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529660446/ana_user.jpg',
     interests: [ 'museums', 'yoga', 'fishing', 'sport', 'food' ],
     isTraveler: false,

   },
   {
     id: 5,
     name: "Antonia",
     age: 50,
     city: "Paris",
     country: "France",
     email: "antonia@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529604395/samples/people/jazz.jpg',
     interests: [ 'museums', 'coffee', 'books', 'yoga', 'sport' ],
     isTraveler: true,

   },
   {
     id: 6,
     name: "Marcia",
     age: 50,
     city: "Paris",
     country: "France",
     email: "marcia@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529611316/pexels-photo-733872.jpg',
     interests: [ 'coffee', 'museums', 'yoga', 'sport', 'books' ],
     isTraveler: true,

   },
   {
     id: 7,
     name: "Carlos",
     age: 57,
     city: "Berlin",
     country: "Germany",
     email: "carlos@gmail.com",
     url: 'https://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529659828/videoblocks-young-man-traveler-with-backpack-viewing-map-in-digital-mobile-phone-relaxing-outdoor-on-background-20s-4k_bb1xs72lb_thumbnail-full01.jpg',
     interests: [ 'yoga', 'dancing', 'fishing', 'sport', 'museums' ],
     isTraveler: true,

   },
   {
     id: 8,
     name: "Gilberto",
     age: 55,
     city: "Berlin",
     country: "Germany",
     email: "gilberto@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529610806/LYB_People_Profile_2808_29.jpg',
     interests: [ 'drinking', 'books', 'museums', 'yoga', 'sport' ],
     isTraveler: true,

   },
   {
     id: 9,
     name: "Junior",
     age: 34,
     city: "Paris",
     country: "France",
     email: "junior@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529611448/paramount-35065-Full-Image_GalleryBackground-en-US-1483994508505._RI_SX940_.jpg',
     interests: [ 'drinking', 'museums', 'hicking', 'sport', 'yoga' ],
     isTraveler: true,

   },
   {
     id: 10,
     name: "Aline",
     age: 33,
     city: "Berlin",
     country: "Germany",
     email: "aline@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529611922/09zali07-vyl3e5b2-12.06.27-ast_ft_female-travel-4263023499-1.jpg',
     interests: [ 'hicking', 'yoga', 'coffee', 'museums', 'sport' ],
     isTraveler: true,

   },
   {
     id: 11,
     name: "Luiz",
     age: 59,
     city: "Brussels",
     country: "Belgium",
     email: "luiz@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612239/depositphotos_164070086-stock-photo-excited-old-man-traveling-in.jpg',
     interests: [ 'hicking', 'yoga', 'coffee', 'sport', 'museums' ],
     isTraveler: true,

   },
   {
     id: 12,
     name: "Antonio",
     age: 29,
     city: "Paris",
     country: "France",
     email: "antonio@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612364/862-05998281en_Masterfile.jpg',
     interests: [ 'fishing', 'books', 'yoga', 'sport', 'museums' ],
     isTraveler: false,

   },
   {
     id: 13,
     name: "Aparecido",
     age: 56,
     city: "Brussels",
     country: "Belgium",
     email: "aparecido@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612558/man_travelling_alone_city.jpg',
     interests: [ 'museums', 'hicking', 'yoga', 'coffee', 'sport' ],
     isTraveler: false,

   },
   {
     id: 14,
     name: "Camila",
     age: 23,
     city: "Brussels",
     country: "Belgium",
     email: "camila@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612685/o-WOMAN-TRAVEL-facebook.jpg',
     interests: [ 'museums', 'hicking', 'yoga', 'coffee', 'sport' ],
     isTraveler: false,

   },
   {
     id: 15,
     name: "Carla",
     age: 27,
     city: "Paris",
     country: "France",
     email: "carla@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529612801/57c98588170000012ac7737c.jpg',
     interests: [ 'yoga', 'dancing', 'fishing', 'museums', 'sport' ],
     isTraveler: false,

   },
   {
     id: 16,
     name: "Denis",
     age: 29,
     city: "Berlin",
     country: "Germany",
     email: "denis@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529660720/drinking-man-background-bottle-water-male-nature-mountain-outdoor-travel-summer-thirsty-person-landscape-adventure-lifestyle-handsome-blue-refreshment-relaxation-tourist-sport-healthy-young-tourism_41whzk0b__F0000.jpg',
     interests: [ 'yoga', 'dancing', 'fishing', 'museums', 'sport' ],
     isTraveler: false,

   },
   {
     id: 17,
     name: "Tiago",
     age: 30,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "tiago@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529660928/travel-man.jpg',
     interests: [ 'museums', 'sport', 'books', 'drinking', 'yoga' ],
     isTraveler: true,

   },
   {
     id: 18,
     name: "Janne",
     age: 35,
     city: "Brussels",
     country: "Belgium",
     email: "janne@gmail.com",
     url: 'https://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529613951/Berlin-Travel-Bucket-List-9-700x432.jpg',
     interests: [ 'museums', 'yoga', 'dancing', 'fishing', 'sport' ],
     isTraveler: false,

   },
   {
     id: 19,
     name: "Loize",
     age: 36,
     city: "Paris",
     country: "France",
     email: "loize@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529614432/n05a7352.jpg',
     interests: [ 'yoga', 'dancing', 'fishing', 'museums', 'sport' ],
     isTraveler: false,

   },
   {
     id: 20,
     name: "Laise",
     age: 40,
     city: "Brussels",
     country: "Belgium",
     email: "laise@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529615066/pose.jpg',
     interests: [ 'yoga', 'dancing', 'fishing', 'sport', 'museums' ],
     isTraveler: false,

   },
   {
     id: 21,
     name: "Paulina",
     age: 37,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "paulina@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529657889/pic.jpg',
     interests: [ 'museums', 'coffee', 'books', 'sport', 'yoga' ],
     isTraveler: false,

   },
   {
     id: 22,
     name: "Iuliia",
     age: 26,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "Iulia@gmail.com",
     url: 'http://res.cloudinary.com/hlupi/image/upload/c_scale,h_350/v1529440628/carme.jpg',
     interests: [ 'yoga', 'dancing', 'fishing', 'sport', 'museums' ],
     isTraveler: false,

   },
   {
     id: 23,
     name: "Jelena",
     age: 31,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "yelena@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529657561/slack-imgs.com.jpg',
     interests: [ 'yoga', 'dancing', 'fishing', 'museums', 'sport' ],
     isTraveler: false,

   },
   {
     id: 24,
     name: "Estabrak",
     age: 32,
     city: "Amsterdam",
     country: "The Netherlands",
     email: "estabrak@gmail.com",
     url: 'http://res.cloudinary.com/aninha/image/upload/c_scale,h_350/v1529661776/esta_user.jpg',
     interests: [ 'yoga', 'dancing', 'museums', 'fishing', 'sport' ],
     isTraveler: false,

   }
]
